name: tz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
  fonts:
    - family: Nunito
      fonts:
        - asset: 'assets/fonts/Nunito/Nunito-Black.ttf'
          weight: 800
        - asset: 'assets/fonts/Nunito/Nunito-ExtraBold.ttf'
          weight: 700
        - asset: 'assets/fonts/Nunito/Nunito-Bold.ttf'
          weight: 600
        - asset: 'assets/fonts/Nunito/Nunito-SemiBold.ttf'
          weight: 500
        - asset: 'assets/fonts/Nunito/Nunito-Medium.ttf'
          weight: 400
        - asset: 'assets/fonts/Nunito/Nunito-Regular.ttf'
          weight: 300
        - asset: 'assets/fonts/Nunito/Nunito-Light.ttf'
          weight: 200
        - asset: 'assets/fonts/Nunito/Nunito-ExtraLight.ttf'
          weight: 100

